###

GET http://localhost:9999/pathGet HTTP/1.1

###

POST http://localhost:9999/pathPost
Content-Type: application/json

{
    "users": [
        {
            "name": "trol",
            "value": "troleto"
        },
        {
            "name": "trol",
            "value": "troleto"
        }
    ]
}