###

GET http://localhost:9999/pathGet HTTP/1.1

###

POST http://localhost:9999/pathPos
Content-Type: application/json

[
  {
    "firstName": "ИмяЧетыре",
    "lastName": "ФамилияЧетыре",
    "middleName": "ОтчествоЧетыре",
    "birthDate": null,
    "birthPlace": "НЕ Меняйте ФИО! пароль и другие данные! Это общая тестовая УЗ!!! Заведите персональную - и её меняйте!!\n\nИ как же личную довести до подтвержденной?",
    "citizenship": "RUS",
    "gender": null,
    "snils": "000-000-600 04",
    "inn": "924651506024",
    "trusted": true,
    "contacts": [
      {
        "type": "EML",
        "value": "EsiaTest004@yandex.ru"
      },
      {
        "type": "MBT",
        "value": "+7(964)5331912"
      },
      {
        "type": "PHN",
        "value": "+7(499)3213213"
      }
    ],
    "documents": [
      {
        "type": "RF_PASSPORT",
        "series": "0006",
        "number": "000111",
        "latinLastName": null,
        "latinFirstName": null,
        "issueId": "006004",
        "issuedBy": "УФМС004",
        "issueDate": "01.01.2004",
        "expireDate": null
      }
    ],
    "addresses": [
      {
        "type": "PLV",
        "addressStr": "край Хабаровский, г Хабаровск, пер Саратовский",
        "countryId": "RUS",
        "zipCode": "680031",
        "region": "Хабаровский",
        "area": null,
        "city": "Хабаровск",
        "district": null,
        "settlement": null,
        "street": "Саратовский",
        "additionArea": null,
        "additionAreaStreet": null,
        "house": "6",
        "building": null,
        "frame": null,
        "flat": "12",
        "fiasCode": null
      }
    ],
    "kids": null,
    "vehicles": null,
    "roles": null
  },
  {
    "firstName": "ИмяЧетыре",
    "lastName": "ФамилияЧетыре",
    "middleName": "ОтчествоЧетыре",
    "birthDate": null,
    "birthPlace": "НЕ Меняйте ФИО! пароль и другие данные! Это общая тестовая УЗ!!! Заведите персональную - и её меняйте!!\n\nИ как же личную довести до подтвержденной?",
    "citizenship": "RUS",
    "gender": null,
    "snils": "000-000-600 04",
    "inn": "924651506024",
    "trusted": true,
    "contacts": [
      {
        "type": "EML",
        "value": "EsiaTest004@yandex.ru"
      },
      {
        "type": "MBT",
        "value": "+7(964)5331912"
      },
      {
        "type": "PHN",
        "value": "+7(499)3213213"
      }
    ],
    "documents": [
      {
        "type": "RF_PASSPORT",
        "series": "0006",
        "number": "000111",
        "latinLastName": null,
        "latinFirstName": null,
        "issueId": "006004",
        "issuedBy": "УФМС004",
        "issueDate": "01.01.2004",
        "expireDate": null
      }
    ],
    "addresses": [
      {
        "type": "PLV",
        "addressStr": "край Хабаровский, г Хабаровск, пер Саратовский",
        "countryId": "RUS",
        "zipCode": "680031",
        "region": "Хабаровский",
        "area": null,
        "city": "Хабаровск",
        "district": null,
        "settlement": null,
        "street": "Саратовский",
        "additionArea": null,
        "additionAreaStreet": null,
        "house": "6",
        "building": null,
        "frame": null,
        "flat": "12",
        "fiasCode": null
      }
    ],
    "kids": null,
    "vehicles": null,
    "roles": null
  },
  {
    "firstName": "ИмяЧетыре",
    "lastName": "ФамилияЧетыре",
    "middleName": "ОтчествоЧетыре",
    "birthDate": null,
    "birthPlace": "НЕ Меняйте ФИО! пароль и другие данные! Это общая тестовая УЗ!!! Заведите персональную - и её меняйте!!\n\nИ как же личную довести до подтвержденной?",
    "citizenship": "RUS",
    "gender": null,
    "snils": "000-000-600 04",
    "inn": "924651506024",
    "trusted": true,
    "contacts": [
      {
        "type": "EML",
        "value": "EsiaTest004@yandex.ru"
      },
      {
        "type": "MBT",
        "value": "+7(964)5331912"
      },
      {
        "type": "PHN",
        "value": "+7(499)3213213"
      }
    ],
    "documents": [
      {
        "type": "RF_PASSPORT",
        "series": "0006",
        "number": "000111",
        "latinLastName": null,
        "latinFirstName": null,
        "issueId": "006004",
        "issuedBy": "УФМС004",
        "issueDate": "01.01.2004",
        "expireDate": null
      }
    ],
    "addresses": [
      {
        "type": "PLV",
        "addressStr": "край Хабаровский, г Хабаровск, пер Саратовский",
        "countryId": "RUS",
        "zipCode": "680031",
        "region": "Хабаровский",
        "area": null,
        "city": "Хабаровск",
        "district": null,
        "settlement": null,
        "street": "Саратовский",
        "additionArea": null,
        "additionAreaStreet": null,
        "house": "6",
        "building": null,
        "frame": null,
        "flat": "12",
        "fiasCode": null
      }
    ],
    "kids": null,
    "vehicles": null,
    "roles": null
  },
  {
    "firstName": "ИмяЧетыре",
    "lastName": "ФамилияЧетыре",
    "middleName": "ОтчествоЧетыре",
    "birthDate": null,
    "birthPlace": "НЕ Меняйте ФИО! пароль и другие данные! Это общая тестовая УЗ!!! Заведите персональную - и её меняйте!!\n\nИ как же личную довести до подтвержденной?",
    "citizenship": "RUS",
    "gender": null,
    "snils": "000-000-600 04",
    "inn": "924651506024",
    "trusted": true,
    "contacts": [
      {
        "type": "EML",
        "value": "EsiaTest004@yandex.ru"
      },
      {
        "type": "MBT",
        "value": "+7(964)5331912"
      },
      {
        "type": "PHN",
        "value": "+7(499)3213213"
      }
    ],
    "documents": [
      {
        "type": "RF_PASSPORT",
        "series": "0006",
        "number": "000111",
        "latinLastName": null,
        "latinFirstName": null,
        "issueId": "006004",
        "issuedBy": "УФМС004",
        "issueDate": "01.01.2004",
        "expireDate": null
      }
    ],
    "addresses": [
      {
        "type": "PLV",
        "addressStr": "край Хабаровский, г Хабаровск, пер Саратовский",
        "countryId": "RUS",
        "zipCode": "680031",
        "region": "Хабаровский",
        "area": null,
        "city": "Хабаровск",
        "district": null,
        "settlement": null,
        "street": "Саратовский",
        "additionArea": null,
        "additionAreaStreet": null,
        "house": "6",
        "building": null,
        "frame": null,
        "flat": "12",
        "fiasCode": null
      }
    ],
    "kids": null,
    "vehicles": null,
    "roles": null
  },
  {
    "firstName": "ИмяЧетыре",
    "lastName": "ФамилияЧетыре",
    "middleName": "ОтчествоЧетыре",
    "birthDate": null,
    "birthPlace": "НЕ Меняйте ФИО! пароль и другие данные! Это общая тестовая УЗ!!! Заведите персональную - и её меняйте!!\n\nИ как же личную довести до подтвержденной?",
    "citizenship": "RUS",
    "gender": null,
    "snils": "000-000-600 04",
    "inn": "924651506024",
    "trusted": true,
    "contacts": [
      {
        "type": "EML",
        "value": "EsiaTest004@yandex.ru"
      },
      {
        "type": "MBT",
        "value": "+7(964)5331912"
      },
      {
        "type": "PHN",
        "value": "+7(499)3213213"
      }
    ],
    "documents": [
      {
        "type": "RF_PASSPORT",
        "series": "0006",
        "number": "000111",
        "latinLastName": null,
        "latinFirstName": null,
        "issueId": "006004",
        "issuedBy": "УФМС004",
        "issueDate": "01.01.2004",
        "expireDate": null
      }
    ],
    "addresses": [
      {
        "type": "PLV",
        "addressStr": "край Хабаровский, г Хабаровск, пер Саратовский",
        "countryId": "RUS",
        "zipCode": "680031",
        "region": "Хабаровский",
        "area": null,
        "city": "Хабаровск",
        "district": null,
        "settlement": null,
        "street": "Саратовский",
        "additionArea": null,
        "additionAreaStreet": null,
        "house": "6",
        "building": null,
        "frame": null,
        "flat": "12",
        "fiasCode": null
      }
    ],
    "kids": null,
    "vehicles": null,
    "roles": null
  },
  {
    "firstName": "ИмяЧетыре",
    "lastName": "ФамилияЧетыре",
    "middleName": "ОтчествоЧетыре",
    "birthDate": null,
    "birthPlace": "НЕ Меняйте ФИО! пароль и другие данные! Это общая тестовая УЗ!!! Заведите персональную - и её меняйте!!\n\nИ как же личную довести до подтвержденной?",
    "citizenship": "RUS",
    "gender": null,
    "snils": "000-000-600 04",
    "inn": "924651506024",
    "trusted": true,
    "contacts": [
      {
        "type": "EML",
        "value": "EsiaTest004@yandex.ru"
      },
      {
        "type": "MBT",
        "value": "+7(964)5331912"
      },
      {
        "type": "PHN",
        "value": "+7(499)3213213"
      }
    ],
    "documents": [
      {
        "type": "RF_PASSPORT",
        "series": "0006",
        "number": "000111",
        "latinLastName": null,
        "latinFirstName": null,
        "issueId": "006004",
        "issuedBy": "УФМС004",
        "issueDate": "01.01.2004",
        "expireDate": null
      }
    ],
    "addresses": [
      {
        "type": "PLV",
        "addressStr": "край Хабаровский, г Хабаровск, пер Саратовский",
        "countryId": "RUS",
        "zipCode": "680031",
        "region": "Хабаровский",
        "area": null,
        "city": "Хабаровск",
        "district": null,
        "settlement": null,
        "street": "Саратовский",
        "additionArea": null,
        "additionAreaStreet": null,
        "house": "6",
        "building": null,
        "frame": null,
        "flat": "12",
        "fiasCode": null
      }
    ],
    "kids": null,
    "vehicles": null,
    "roles": null
  }
]